In [ ]:
!pip config set global.cert /root/alight-root.pem
!pip config list



In [ ]:
cat /root/.config/pip/pip.conf

In [ ]:
!pip install imblearn --index-url https://artifactory.alight.com/artifactory/api/pypi/python-pypi-remote/simple

In [ ]:
%pip install transformers --index-url https://artifactory.alight.com/artifactory/api/pypi/python-pypi-remote/simple

##### Ipywidgets is supposed to help with the transformers download status but SageMaker doesn't have it and it doesn't insall correct

In [ ]:
# %pip install ipywidgets --index-url https://artifactory.alight.com/artifactory/api/pypi/python-pypi-remote/simple

In [16]:
import os
import urllib

from getpass import getpass
from transformers import pipeline

### Workaround for accessing Huggingface through proxy

In [ ]:
username = urllib.parse.quote(input("Input your username: "))

In [ ]:
password = urllib.parse.quote(getpass("Input your password: "))

In [ ]:
proxy = f"https://{username}:{password}@proxycachest.hewitt.com:3228"

os.environ['http_proxy'] = proxy
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy

##### Remove proxy if you need to use pip install from Artifactory again

In [ ]:
# del os.environ['http_proxy']
# del os.environ['HTTP_PROXY']
# del os.environ['https_proxy']
# del os.environ['HTTPS_PROXY']

### Workaround for ipywidgets error

ImportError: IProgress not found. Please update jupyter and ipywidgets.

In [ ]:
import transformers
import logging
transformers.logging.get_verbosity = lambda : logging.NOTSET

In [ ]:
print('a')

In [ ]:
unmasker = pipeline('fill-mask', model='distilbert-base-uncased-finetuned-sst-2-english')

In [ ]:
!ls -la .cache/huggingface/transformers/

In [ ]:
unmasker("Hello I'm a [MASK] model.")

In [ ]:
!ls -la .cache/huggingface/transformers/

In [2]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [4]:

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351695, -0.51327264, -0.88845724, ..., -0.74748856,
        -0.7531474 ,  0.91964495],
       [-0.8720835 , -0.50543964, -0.9444668 , ..., -0.85847497,
        -0.71745366,  0.8808299 ]], dtype=float32)>

In [5]:
df['transcripts'][0]

NameError: name 'df' is not defined

In [35]:
len(df['transcripts'])

17094

In [63]:
#text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
text_input=['basic life insurance total cost per pay period medical per pay period health saving account per pay period dental dental per pay period going complete enrollment updated enrollment benefit verify updated updated medical coverage well delta dental perfect welcome question welcome calling bmo financial group benefit center great rest day welcome']
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

In [75]:
outputs['pooled_output']

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.6940458 , -0.44220814, -0.935502  ,  0.57507324,  0.670459  ,
        -0.07321282,  0.58507043,  0.28052   , -0.78391635, -0.99992645,
        -0.5152486 ,  0.93915474,  0.9283507 ,  0.68803227,  0.8074385 ,
        -0.6273166 , -0.07497698, -0.4284063 ,  0.38014022,  0.302668  ,
         0.71399987,  0.9999958 , -0.01282584,  0.18802421,  0.42108536,
         0.98186743, -0.6684413 ,  0.80844814,  0.8768047 ,  0.6731241 ,
        -0.34324026,  0.329083  , -0.9663469 , -0.19314569, -0.95903295,
        -0.970115  ,  0.24764428, -0.5384442 , -0.01562017,  0.03690729,
        -0.7665244 ,  0.3296602 ,  0.99995   ,  0.23324023,  0.5165461 ,
        -0.11106659, -0.99999905,  0.1012535 , -0.6960033 ,  0.9124028 ,
         0.8517275 ,  0.8493588 ,  0.14279743,  0.42721292,  0.47575605,
         0.09140716,  0.01426685,  0.05951454, -0.3205976 , -0.47954822,
        -0.5636088 ,  0.45171618, -0.91141605, -0.7886358 ,  0.9356065 ,
 

In [77]:
#t=['basic life insurance total cost per pay period medical per pay period health saving account per pay period dental dental per pay period going complete enrollment updated enrollment benefit verify updated updated medical coverage well delta dental perfect welcome question welcome calling bmo financial group benefit center great rest day welcome']
a=[]
for i in range(0,len(df['transcripts'])):
        t=bert_preprocess([df['transcripts'][i]])
        t=bert_encoder(t)
        a.append(t['pooled_output'])



KeyboardInterrupt: 

In [76]:
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [58]:
np.array(df['transcripts']).shape

(17094,)

In [56]:
import numpy as np

np.array(a).shape

(2, 1, 768)

In [4]:
e = get_sentence_embeding([
    "banana", 
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])

In [43]:
outputs

{'sequence_output': <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
 'pooled_output': <KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'keras_layer_1')>,
 'default': <KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'keras_layer_1')>,
 'encoder_outputs': [<KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'keras_layer_1')>,
  <KerasTensor: shape=(None, 128, 768) dtype=fl

In [38]:
# Bert layers
text_input = tf.keras.layers.Input(shape=[], dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
#l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(179, activation='sigmoid', name="output")(outputs['pooled_output'])

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [29]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
text (InputLayer)               [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           text[0][0]                       
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'sequence_output':  109482241   keras_layer[2][0]                
                                                                 keras_layer[2][1]                
                                                                 keras_layer[2][2]                
____________________________________________________________________________________________

In [30]:
import pandas as pd

df=pd.read_csv('/root/AWS_data/Phase 2/PST_Drivers/PST_Topics_Feature/PST_V1.3/df_PST_BILSTM_Bmo_Meijer_V1_2.csv',usecols=['transcripts','PrimaryTopic','PrimarySubtopic','Drivers'],low_memory=True)
df

transcripts  \
0      calling bmo financial group benefit center nam...   
1      calling bmo financial group benefit center nam...   
2      calling bmo financial group benefit center nam...   
3      hello calling bmo financial benefit center nam...   
4      calling benefit center education assist help t...   
...                                                  ...   
17089  good afternoon calling benefit center name pro...   
17090  calling reward service center pleasure speakin...   
17091  calling meijer reward service center name assi...   
17092  calling reward service center pleasure speakin...   
17093  calling reward service center pleasure speakin...   

                             PrimarySubtopic                    PrimaryTopic  \
0                                    MEDICAL                              HW   
1                            OTHER_QUESTIONS                 OTHER_QUESTIONS   
2      ELIGIBILITY INQUIRIES (NO ENROLLMENT)         QUALIFIED STATUS CHANGE   
3                            OTHER_QUESTIONS                 OTHER_QUESTIONS   
4                                    MEDICAL                              HW   
...                                      ...                             ...   
17089                COMMUNICATION MATERIALS                    CM - GENERAL   
17090                  PROCESSED TRANSACTION  DC - DISTRIBUTIONS/INSTALLMENT   
17091                    CASE STATUS INQUIRY                    CM - GENERAL   
17092                        PASSWORD ISSUES                     CM - ACCESS   
17093                    CASE STATUS INQUIRY                    CM - GENERAL   

                                                 Drivers  
0              HEALTH_COVERAGE & BENEFIT OPTIONS_MEDICAL  
1      CROSS SOLUTION_CALL CONNECTION ISSUES_UNEXPECT...  
2          HEALTH_LIFE EVENT_ELIGIBILITY/PLAN PROVISIONS  
3      CROSS SOLUTION_CALL CONNECTION ISSUES_UNEXPECT...  
4              HEALTH_COVERAGE & BENEFIT OPTIONS_MEDICAL  
...                                                  ...  
17089   CROSS SOLUTION_GENERAL_OTHER FORM/COMMUNICATIONS  
17090  401K_DISTRIBUTION/ROLLOVER_INITIATE DISTRIBUTI...  
17091      CROSS SOLUTION_CASE STATUS_OTHER CASE INQUIRY  
17092      CROSS SOLUTION_ACCESS_PASSWORD/PIN/OTC ISSUES  
17093      CROSS SOLUTION_CASE STATUS_OTHER CASE INQUIRY  

[17094 rows x 4 columns]

In [31]:
X=df['transcripts'].copy()
y=df['Drivers'].copy()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y.values)
mapping = dict(zip(range(len(le.classes_)),le.classes_))
mapping

{0: '401K_CONTRIBUTIONS_CHANGE CONTRIBUTION AMOUNT',
 1: '401K_CONTRIBUTIONS_ELIGIBILITY/ENROLLMENT',
 2: '401K_CONTRIBUTIONS_FUND PERFORMANCE & FEES',
 3: '401K_CONTRIBUTIONS_FUND TRANSFERS/REALLOCATIONS',
 4: '401K_DISTRIBUTION/ROLLOVER_INITIATE DISTRIBUTION/ROLLOVER',
 5: '401K_DISTRIBUTION/ROLLOVER_PAYMENT STATUS/DELIVERY/CORRECTION',
 6: '401K_DISTRIBUTION/ROLLOVER_POLICY/PROVISIONS/ELIGIBILITY',
 7: '401K_DISTRIBUTION/ROLLOVER_ROLLOVER INTO THE PLAN',
 8: '401K_GENERAL_ACCOUNT BALANCE',
 9: '401K_GENERAL_ACCOUNT STATEMENTS',
 10: '401K_GENERAL_POLICY/PROVISIONS/ELIGIBILITY',
 11: '401K_HARDSHIP WITHDRAWAL_INITIATE WITHDRAWAL',
 12: '401K_HARDSHIP WITHDRAWAL_PAYMENT STATUS/DELIVERY/CORRECTION',
 13: '401K_HARDSHIP WITHDRAWAL_POLICY/PROVISIONS/ELIGIBILITY',
 14: '401K_HARDSHIP WITHDRAWAL_SUPPORTING DOCUMENTATION STATUS/INQUIRY',
 15: '401K_LOANS_INITIATE LOAN',
 16: '401K_LOANS_LOAN PROCESS/ ELIGIBILITY',
 17: '401K_LOANS_LOAN REPAYMENT & PAYOFF',
 18: '401K_LOANS_LOAN REQUEST STAT

In [32]:
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [33]:
len(X_train)

11452

In [34]:
len(y_train)

11452

In [35]:
y_train.shape

(11452,)

In [39]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=METRICS)

In [40]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10


ValueError: in user code:

    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:835 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.6/site-packages/keras/engine/training.py:792 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.6/site-packages/keras/engine/compile_utils.py:457 update_state
        metric_obj.update_state(y_t, y_p, sample_weight=mask)
    /usr/local/lib/python3.6/site-packages/keras/utils/metrics_utils.py:73 decorated
        update_op = update_state_fn(*args, **kwargs)
    /usr/local/lib/python3.6/site-packages/keras/metrics.py:177 update_state_fn
        return ag_update_state(*args, **kwargs)
    /usr/local/lib/python3.6/site-packages/keras/metrics.py:1366 update_state  **
        sample_weight=sample_weight)
    /usr/local/lib/python3.6/site-packages/keras/utils/metrics_utils.py:623 update_confusion_matrix_variables
        y_pred.shape.assert_is_compatible_with(y_true.shape)
    /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 179) and (None, 1) are incompatible
